import type { CharacterSubmitRequest } from '../types'
import { request } from './client'

/**
 * Character API.
 *
 * Source: contractRules.md §17. A HIDER may submit exactly one character per
 * game, so there is deliberately no update/re-submit call here — the backend
 * rejects duplicates with CHARACTER_ALREADY_SUBMITTED.
 *
 * The response is intentionally untyped beyond `characterId`: the qrToken is
 * generated by the backend (§18) and is not consumed by the hider feature.
 */

export type SubmitCharacterResponse = {
  characterId: number
}

export function submitCharacter(
  gameId: number | string,
  payload: CharacterSubmitRequest,
) {
  return request<SubmitCharacterResponse>(
    `/games/${encodeURIComponent(String(gameId))}/characters`,
    { method: 'POST', body: payload, auth: 'participant' },
  )
}
